<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.34.0.3385" />
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
  </ItemGroup>
</Project>