<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>4f621fd3-47de-49b4-8c1c-34e1cbb89c74</UserSecretsId>
    <StartupObject></StartupObject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Figgle.Fonts" />
    <PackageReference Include="WebAgentShared.LibProjectsApi" />
    <PackageReference Include="WebSystemTools.ApiKeyIdentity" />
    <PackageReference Include="WebSystemTools.MediatorTools" />
    <PackageReference Include="WebSystemTools.SerilogLogger" />
    <PackageReference Include="WebSystemTools.SignalRMessages" />
    <PackageReference Include="WebSystemTools.SwaggerTools" />
    <PackageReference Include="WebSystemTools.TestToolsApi" />
    <PackageReference Include="WebSystemTools.WindowsServiceTools" />
  </ItemGroup>


</Project>
